sudo: false
language: rust
rust:
- stable
- beta
- nightly
script:
- |
  cargo build --verbose &&
  case $TRAVIS_RUST_VERSION in
    nightly)  cargo test --verbose --features unstable ;;
    *)        cargo test --verbose ;;
  esac &&
  cargo doc --no-deps
notifications:
  email:
    on_success: never
os:
- linux
- osx
after_success: |
  [ $TRAVIS_BRANCH = "master" ] &&
  [ $TRAVIS_PULL_REQUEST = "false" ] &&
  [ $TRAVIS_RUST_VERSION = "stable" ] &&
  [ `uname` = "Linux" ] &&
  echo '<meta http-equiv=refresh content=0;url=typeinfo/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push --force https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: A7wRIYzvkG1KIu5nc3SIT2EGszQs/Lu2KZPIMo99FdVbPjVhr6l9Qswbt2S8VAP1mJulD8dGqhuaTWFqoUF6L6uf1leG3FKkD5p3wf8MgfVk0qTQa7XhnB6QJXdghJ0VE0AnEpDk3lJAaun2mQCkmxklOsGHkX9Vg7fORSSEnZbyNERxWegCeLIle9WyJjfMvaJWOI2Yzt3KPSabIFdRMW0rIS3KjEGKSzaqa+1AtrzAR0Y7XJb2sLGnXLQUrt/crO8TG/2i3E0eErAGSS2uYnA7RO7rCUQIxs0nOIHjSXhWTt8kZNrSmbNtjZaoofv2ZDJt3fdqpM7EtpyLQWPJJNRaLjGV7WJmLzqkmW5yvuRBRgCP/b+G2TOtnOL5ECAq5Z3b5bWJRAeo9vC1javQeNwW8JZTSMZimRkeeEFA+g6rg7pvWwt2EgxOHIUKIbBFvh0ci0FCAO1vKhme6NJj7G+Y6E72MfBd6TCE8LEwE+TPjvkaItYLPURzwPHKobO7NAJBxiY2YdwA10TLbtcLxAooY+j9VQ6cuEj2a2HRFI7ExiL49e4kTFU3MQ/L5M3xQs6Kt8ioCnawNxDIHPcDCrF6QRQ99RAFJqzecgEw3urihb15Z5fKgH9w7eodGreH4OQ1iI1SkCTtxtnQLWpxqyfFLDV6A6USt072cIFoftk=
